github.com/RodneyShag

Yes. The "finally" block (still) gets executed when the "try" block exits.
